name: Metrics
on:
  # Scheduled updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs workflow on each commit (on the master branch)
  push: {branches: ["master"]}
jobs:
  github-metrics-base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Core/general
          user: pasqu4le
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_output: svg
          config_timezone: Europe/Rome
          config_gemoji: yes
          config_padding: 0, 8 + 11%
          filename: metrics/base.svg
          # Base
          base: header, activity, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member

  github-metrics-isocal:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Core/general
          user: pasqu4le
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_output: svg
          config_timezone: Europe/Rome
          config_gemoji: yes
          config_padding: 0, 8 + 11%
          filename: metrics/isocal.svg
          # Isometric commit calendar
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  github-metrics-lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Core/general
          user: pasqu4le
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_output: svg
          config_timezone: Europe/Rome
          config_gemoji: yes
          config_padding: 0, 8 + 11%
          filename: metrics/lang.svg
          # Most used languages
          base: ""
          plugin_languages: yes
          plugin_languages_threshold: 1%

  github-metrics-follow:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Core/general
          user: pasqu4le
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_output: svg
          config_timezone: Europe/Rome
          config_gemoji: yes
          config_padding: 0, 8 + 11%
          filename: metrics/follow.svg
          # Follow-up of issues and pull requests
          base: ""
          plugin_followup: yes
